//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronozoom.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronozoom.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE CreateCollectionStats
        ///	@Collection_Id UNIQUEIDENTIFIER
        ///AS
        ///BEGIN
        ///	DECLARE @exhibit_cnt INT
        ///	DECLARE @content_item_cnt INT
        ///	DECLARE @chld_size INT
        ///	DECLARE @root_id UNIQUEIDENTIFIER
        ///	DECLARE @current_id UNIQUEIDENTIFIER
        ///	DECLARE @successor_id UNIQUEIDENTIFIER
        ///	DECLARE @root_level TABLE (
        ///		Id UNIQUEIDENTIFIER
        ///	)
        ///	INSERT INTO @root_level SELECT Id FROM Timelines WHERE Depth = 0 AND Collection_ID =  @Collection_Id
        ///	DECLARE cur CURSOR FOR SELECT Id FROM @root_level
        ///	OPEN cur
        ///	FET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateCollectionStats {
            get {
                return ResourceManager.GetString("CreateCollectionStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE CreateDepthFields
        ///	@collection_id UNIQUEIDENTIFIER
        ///AS 
        ///BEGIN
        ///	DECLARE @current_depth INT
        ///	DECLARE @current_level_size INT
        ///	DECLARE @current_id UNIQUEIDENTIFIER
        ///	DECLARE @current_level TABLE (
        ///		Id UNIQUEIDENTIFIER
        ///	)
        ///	DECLARE @next_level TABLE (
        ///		Id UNIQUEIDENTIFIER
        ///	)
        ///	DECLARE cur CURSOR FOR SELECT Id FROM @current_level
        ///	SET @current_depth = 0
        ///	INSERT INTO @current_level SELECT Id FROM Timelines WHERE Collection_Id = @collection_id AND Timeline_Id = CAST(CAST(0 AS BINARY)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDepthFields {
            get {
                return ResourceManager.GetString("CreateDepthFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE PostOrderTraversal
        ///	@timeline_id UNIQUEIDENTIFIER,
        ///	@first_node_in_subtree UNIQUEIDENTIFIER OUTPUT
        ///AS
        ///BEGIN
        ///	DECLARE @set_first_node_in_subtree BIT 	
        ///	DECLARE @chld_cnt INT
        ///	DECLARE @current_id UNIQUEIDENTIFIER
        ///	DECLARE @previous_id UNIQUEIDENTIFIER
        ///	DECLARE @current_first_node_in_subtree UNIQUEIDENTIFIER
        ///	DECLARE cur CURSOR FOR SELECT Id FROM Timeline WHERE Timeline_Id = @timeline_id
        ///	DECLARE @chld TABLE (
        ///		Id UNIQUEIDENTIFIER
        ///	)
        ///	SET @set_first_node_in_subtree = 0
        ///	SELECT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePostOrderIndex {
            get {
                return ResourceManager.GetString("CreatePostOrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE TimelineSubtreeQuery
        ///	@Collection_Id UNIQUEIDENTIFIER,
        ///	@LCA UNIQUEIDENTIFIER,
        ///	@min_span DECIMAL,
        ///	@startTime DECIMAL,
        ///	@endTime DECIMAL,
        ///	@max_elem INT
        ///AS
        ///BEGIN
        ///	DECLARE @return_entire_subtree BIT
        ///	DECLARE @subtree_size INT
        ///	DECLARE @current_level_cnt INT
        ///	DECLARE @cnt INT
        ///	DECLARE @num_ge_min_span INT
        ///	DECLARE @current_id UNIQUEIDENTIFIER
        ///	DECLARE @current_level TABLE (
        ///		Id UNIQUEIDENTIFIER
        ///	)
        ///	DECLARE @next_level TABLE (
        ///		Id UNIQUEIDENTIFIER
        ///	)
        ///	DECLARE @results TABLE (
        ///		Id UNIQUEIDE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimelineSubtreeQuery {
            get {
                return ResourceManager.GetString("TimelineSubtreeQuery", resourceCulture);
            }
        }
    }
}
