//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chronozoom.Entities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chronozoom.Entities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE FUNCTION Minimum (@x decimal, @y decimal)
        ///RETURNS decimal
        ///AS
        ///BEGIN
        ///	 IF @x &lt;= @y
        ///        RETURN @x
        ///    ELSE
        ///        RETURN @y
        ///
        ///	RETURN NULL --Never Hits
        ///END.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE TimelineSubtreeQuery
        ///	@collection_id UNIQUEIDENTIFIER,
        ///	@start_time DECIMAL,
        ///	@end_time DECIMAL,
        ///	@min_span DECIMAL,
        ///	@lca_id UNIQUEIDENTIFIER,
        ///	@max_elem INT,
        ///	@path_from_root BIT
        ///AS
        ///BEGIN
        ///	DECLARE @next_year decimal
        ///	DECLARE @cid UNIQUEIDENTIFIER -- current timeline id
        ///	DECLARE @pid UNIQUEIDENTIFIER -- parent  timeline id
        ///	DECLARE @path TABLE (Id UNIQUEIDENTIFIER, Depth INT) -- path from root to lca
        ///	DECLARE @path_with_siblings TABLE (Id UNIQUEIDENTIFIER, Depth INT) -- for e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TimelineSubtreeQuery {
            get {
                return ResourceManager.GetString("TimelineSubtreeQuery", resourceCulture);
            }
        }
    }
}
