//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apicon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Source\\Chronozoom.UI\\bin\\Chronozoom." +
            "UI.XML")]
        public string MemberPath {
            get {
                return ((string)(this["MemberPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Source\\Chronozoom.Entities\\bin\\Chron" +
            "ozoom.Entities.XML")]
        public string EntityPath {
            get {
                return ((string)(this["EntityPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M:Chronozoom.UI.IChronozoomSVC.")]
        public string MemberClass {
            get {
                return ((string)(this["MemberClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T:Chronozoom.Entities.")]
        public string EntityTypeClass {
            get {
                return ((string)(this["EntityTypeClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:Chronozoom.Entities.")]
        public string EntityPropClass {
            get {
                return ((string)(this["EntityPropClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Doc\\Chronozoom_REST_API_top.md")]
        public string TopMatter {
            get {
                return ((string)(this["TopMatter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Doc\\tools\\apicon\\apicon\\output\\Chron" +
            "oZoom_REST_API.md")]
        public string OutFile {
            get {
                return ((string)(this["OutFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Doc\\ChronoZoom_REST_API.md")]
        public string OutFile2 {
            get {
                return ((string)(this["OutFile2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>entityPropRgx</string>
  <string>RemoveRITree</string>
  <string>AddRITreeWithIndex</string>
  <string>Properties.Resources</string>
  <string>RemoveBetaFields</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExcludeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcludeList"]));
            }
        }
    }
}
