//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xslcon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Source\\Chronozoom.UI\\bin\\Chronozoom." +
            "UI.XML")]
        public string MemberPath {
            get {
                return ((string)(this["MemberPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Source\\Chronozoom.Entities\\bin\\Chron" +
            "ozoom.Entities.XML")]
        public string EntityPath {
            get {
                return ((string)(this["EntityPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M:Chronozoom.UI.IChronozoomSVC.")]
        public string MemberClass {
            get {
                return ((string)(this["MemberClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M:Chronozoom\\.UI\\.IChronozoomSVC\\.\\w*")]
        public string MemberRgx {
            get {
                return ((string)(this["MemberRgx"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T:Chronozoom.Entities.")]
        public string EntityTypeClass {
            get {
                return ((string)(this["EntityTypeClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T:Chronozoom\\.Entities\\.\\w*")]
        public string EntityTypeRgx {
            get {
                return ((string)(this["EntityTypeRgx"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:Chronozoom.Entities.")]
        public string EntityPropClass {
            get {
                return ((string)(this["EntityPropClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\ChronoZoom\\Doc\\Chronozoom_REST_API_top.md")]
        public string TopMatter {
            get {
                return ((string)(this["TopMatter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\v-wfren\\Documents\\GitHub\\docteam\\xslcon\\xslcon\\output\\ChronoZoom_REST_AP" +
            "I.md")]
        public string OutFile {
            get {
                return ((string)(this["OutFile"]));
            }
        }
    }
}
