//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThumbGen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=ycbhd8cx5r.database.windows.net;initial catalog=CZFox; persist securi" +
            "ty info=True; user id=czpostbeta; password=ChronoZo)m;multipleactiveresultsets=T" +
            "rue;App=EntityFramework")]
        public string SourceConnectionString {
            get {
                return ((string)(this["SourceConnectionString"]));
            }
            set {
                this["SourceConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://czbeta.blob.core.windows.net/images/")]
        public string AzureBlobUrl {
            get {
                return ((string)(this["AzureBlobUrl"]));
            }
            set {
                this["AzureBlobUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GuOeSK06XNtEh40CoXUhQUKhPXfxnTvzdY7ZwzGruRmCYA221htHIbeeZ4PC6YU9WZ5IGHLkQTpcxVIBX" +
            "1WSYw==")]
        public string AccessKeyToBlob {
            get {
                return ((string)(this["AccessKeyToBlob"]));
            }
            set {
                this["AccessKeyToBlob"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512,512")]
        public global::System.Windows.Size InitialSize {
            get {
                return ((global::System.Windows.Size)(this["InitialSize"]));
            }
            set {
                this["InitialSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("czbeta")]
        public string AzureAccountName {
            get {
                return ((string)(this["AzureAccountName"]));
            }
            set {
                this["AzureAccountName"] = value;
            }
        }
    }
}
