// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Procs"), System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Proc")]
    public sealed partial class ProgressiveLoadStoredProcs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProgressiveLoadStoredProcs));
        
        string IMigrationMetadata.Id
        {
            get { return "201306110453343_ProgressiveLoadStoredProcs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
