// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ToursUserMissingMaxLen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToursUserMissingMaxLen));
        
        string IMigrationMetadata.Id
        {
            get { return "201306072040327_ToursUserMissingMaxLen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
