// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ToursDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToursDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201306040017265_ToursDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
