// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TitleLength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TitleLength));
        
        string IMigrationMetadata.Id
        {
            get { return "201305282325585_TitleLength"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
