// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TimelineSubtreeQueryStoredProc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimelineSubtreeQueryStoredProc));
        
        string IMigrationMetadata.Id
        {
            get { return "201305212147255_TimelineSubtreeQueryStoredProc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
