// <auto-generated />
namespace Chronozoom.Entities
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCollectionMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCollectionMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201404222359341_AddCollectionMembers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
